apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.space_NAME}}
  name: {{.Values.app_NAME}}
  labels:
    app : {{.Values.app_NAME}}
spec:
  selector:
    app: {{.Values.app_NAME}}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: {{.Values.app_PORT}}
      name: default-port
    - port: 443
      protocol: TCP
      targetPort: 443
      nodePort: {{.Values.ssl_PORT}}
      name: ssl-port
  type: NodePort
